explosions:
  concrete-explode-chance: 10

guns:
  autoshoot: true
  # This will allow bullets to be used from the inventory; if off, bullets are only used from the offhand. Turn off
  # if this gets really laggy when shooting
  use-bullets-from-inv: true
  # Min range is intended to balance things a little more; this removes it and allows you to shoot at any distance
  # within max range
  min-range-on: true
  energy-rifle-explosions: false

space:
  # This will define the spawn rate for titanium/segganesson meteors. It is defined as a max of meteors-per-chunk
  # meteors that each have a chance of meteor-spawn-rate percent of being generated. There is a segganesson-chance
  # that a meteor will be a segganesson meteor instead of a titanium meteor
  meteor-spawn-rate: 20
  meteors-per-chunk: 1
  segganesson-chance: 15
  # The y height that FLOX will teleport you to space
  tp-height: 100

suits:
  # This will spawn blue particles underneath you when flying with a power suit
  flight-particles: true
  # If this is true, the Element Forge will use iron blocks instead of netherite blocks for the corners
  legacy-element-forge: false
